### ISSUE TITLE
Is there a way to respectively perform findIsotopes to each phenodata class?

### ISSUE THREAD

**Issue by YonghuiDong** [sneumann/CAMERA#25]
My **xset** includes 3 groups of samples, and I want to perform  `findIsotopes ` function to each group rather than altogether. Is there a way to do that?

Another perspective of this question is that is it possible to create a subsets of **an** object according to phenodata class?

> an <- xsAnnotate(xset )
> an@xcmsSet@phenoData$class
>  [1] A A B B C C
Levels: A B C 

Thanks a lot.

**Comment by YonghuiDong** [comment]
Thanks. I have found a way to do it.

**Comment by sneumann** [comment]
Hi, you were close, after the split() you need to `group(xsetA)`.

**Comment by YonghuiDong** [comment]
@sneumann Thanks a lot for your help.
