### ISSUE TITLE
Vignettes: code not visible

### ISSUE THREAD

**Issue by antonwnk** [sneumann/CAMERA#42]
The vignettes found  [here](https://bioconductor.org/packages/release/bioc/vignettes/CAMERA/inst/doc/IsotopeDetectionVignette.pdf) (isotope detection) and [here](https://bioconductor.org/packages/release/bioc/vignettes/CAMERA/inst/doc/compoundQuantilesVignette.pdf) (compound quantiles) have code which does not wrap around when reaching the border of the page, rendering parts of function calls unreadable.

Reading the `.Rnw` files at https://github.com/sneumann/CAMERA/tree/master/vignettes directly in the meanwhile.

**Comment by sneumann** [comment]
Hi, thanks for the hint. If you want, you can edit the `*.Rnw` and add line breaks,
that should even work in the github online editor. That pull request would be highly welcome. 
Yours, Steffen

**Comment by antonwnk** [comment]
Thanks for writing back!
It didn't occur to me that I could fix it myself! Need to work on that open-source mindset.

Best,
Anton

**Comment by sneumann** [comment]
That was a nice low-hanging fruit to get addicted to the Open Source mindset.
Thanks for the contribution, Yours, Steffen
