### ISSUE TITLE
getReducedPeaklist values not reported

### ISSUE THREAD

**Issue by korseby** [sneumann/CAMERA#48]
as reported by Christelle BONNEFOY ...

We need to fix a bug that...

when it is set to FALSE the value for the sample are not reported.
table_red<-getReducedPeaklist(xsaFCIA, intval = "maxo", method = "maxint",cleanup = FALSE,default.adduct.info = "maxint")
 
when it is set to TRUE, the value for the sample are reported.
table_red<-getReducedPeaklist(xsaFCIA, intval = "maxo", method = "maxint",cleanup = TRUE,default.adduct.info = "maxint")

**Comment by korseby** [comment]
I went through the code and only found some minor things that have changed in one of the last R-versions.

I also noticed that your parameters to the function were not quite right. I think it should be like this:

table_red<-getReducedPeaklist(xsaFCIA, method="maxint", intval="into", default.adduct.info=“maxint”, cleanup=TRUE)

Just to make 100% sure. cleanup=TRUE changes all NA to 0 and all values below 0 to 0. If you do not want that, you have to set cleanup=FALSE.

In order to test the code, please do the following:

detach("package:CAMERA", unload = TRUE)
install.packages(“devtools”)
library(devtools)
devtools::install_github("sneumann/CAMERA", ref="reducedPeaklist”)
library(CAMERA)

Otherwise I couldn’t find any errors in the code.

**Comment by cbonnefoy** [comment]
I have had difficulties to install the corrected version but  I am now working with 1.43.2 and the getReducedPeaklist function  with CLEANUP = FALSE is now ok for me : the value are reported.

I work with « maxo » and not « into » because I don’t trust fillpeaks at the moment.

**Comment by korseby** [comment]
Great that it works now. I will submit a pull request so the changes are in main soon.

Using `maxo` is of course perfectly fine.

Thank you for your report and stay healthy.
