### ISSUE TITLE
misunderstanding between "O" and "0"

### ISSUE THREAD

**Issue by shutinet** [sneumann/CAMERA#60]
Hi, 
In the neutral loss file, the oxygen in "H2O" was replaced by a "0". Could you correct it?
Sebastien

**Comment by sneumann** [comment]
Hi Sebastian, 

That's an embarassing one, good catch ! You are talking about this one: 
https://github.com/sneumann/CAMERA/blob/cbc9cdb2eba6438434c27fec5fa13c9e6fdda785/inst/lists/neutralloss.csv#L5
Actually, you could fix that yourself (github rules!), by going to the file (link above) 
and hit the "edit" / pencil button. Then we will get a pull request, check it, and accept it. 
Actually takes longer to describe than to do. 
I have applied the fix now, but can talk you through that process next time
in case you are curious. 

Thanks, 
Yours, Steffen
