### ISSUE TITLE
False negatives, losing peaks when using xsAnnotate on an xcmsSet

### ISSUE THREAD

**Issue by jmorim** [sneumann/CAMERA#64]
I have this peak that's detected by xcms
![image](https://user-images.githubusercontent.com/34515725/100166645-2d48a700-2e8b-11eb-91a6-e074bc32648b.png)
But when I run xsAnnotate on the xcmsSet object, this peak goes away. It's an obvious peak, I can see it in the TIC.
Any tips on troubleshooting why it goes away?

**Comment by jmorim** [comment]
It was removed because grouping specified minFraction = 0.5, while this peak was only present in one file. I'd like to keep it so I lowered minFraction to 0.

**Comment by sneumann** [comment]
Ah, that explains it. Thanks for providing the solution as well ! Yours, Steffen
