### ISSUE TITLE
Please could somebody outline how the number of pcgroups are calculated and why a feature might be in the same pcgroup as another?

### ISSUE THREAD

**Issue by Pembs** [sneumann/CAMERA#79]
I would be grateful if somebody could please direct me to a website which explains how the number of pcgroups are determined and why a feature might have the same pcgroup as another? I've been searching for a bit and haven't come across an explanation. Thank you

**Comment by sneumann** [comment]
Hi, please consult the following paper:
  Kuhl, C., Tautenhahn, R., Boettcher, C., Larson, T. R. and Neumann,
  S. CAMERA: an integrated strategy for compound spectra extraction and
  annotation of liquid chromatography/mass spectrometry data sets.
  Analytical Chemistry, 84:283-289 (2012)
Yours, 
Steffen
