### ISSUE TITLE
pcgroup clarification

### ISSUE THREAD

**Issue by apulvino** [sneumann/CAMERA#81]
Is the pcgroup ID/value is equivalent to ChemSpider database ID/value? I don't see clarification on whether this is the case or not in the CAMERA documentation and only allusions to it in the documentation from other packages... Thanks ahead for the clarification!

**Comment by stanstrup** [comment]
Nope. The pcgroup number doesn't hold an significance itself. All it says is that features with the same pcgroup are probably from the same molecule based on the correlation analysis the functions have done.

**Comment by apulvino** [comment]
do you know if it's possible to not provide ionization for every mz and intensity value you have for a run of the basic sirius command (ie. sirius [OPTIONS] -z <PARENTMASS> -i <IONIZATION> -1 <MS FILE> -2 <MS/MS FILE>)?

**Comment by stanstrup** [comment]
I am not using these tools myself so I cannot help you.
I meant complex in the sense that what they do is a (internally) sophisticated process. I don't think they are that difficult to learn. But what is very important is that they are not trusted to provide truth. There is so much BS published where people use these tools without critical thinking about the likelihood of the results. Identification needs to be verified by old fashioned methods, e.g. standards and considering the alternative structures that are as plausible as whatever top candidate you get.
You won't find any magic tool that just spits out a list of names you can sensibly use without manually curation. Those that do that provide only noise to the literature.
But this is getting far outside the scope of this issue tracker....

**Comment by apulvino** [comment]
I appreciate the resolution! I have more of an NGS-focused data analysis background and so this was useful insight regarding the state of the field comparatively.
